### ISSUE TITLE
Shanling Firmware Theme edit or Repack tool

### ISSUE THREAD

**Issue by tenshi0xx** [npmania/shanling_fw_tools#1]
First of all, thanks for making this tool. I'm wondering if there's a way to repack the unpacked firmware, or can you make a script to repack it? thanks in advance.

**Comment by npmania** [comment]
https://github.com/npmania/X1000/tree/master/external/recovery/server-side
Before running `make`, you should put two files: `system.ubi`, `xImage` under `server-side/image/nand/`.

To build `system.ubi`, you can run command below:
```sh
mkfs.ubifs -d system -e 0x1F000 -c 660 -m 0x800 -o system.ubi
```
where system is ubifs-root directory modified.
Some people claimed one of the flag should be `-c 720`, but 660 worked for me.

**Comment by tenshi0xx** [comment]
> https://github.com/npmania/X1000/tree/master/external/recovery/server-side Before running `make`, you should put two files: `system.ubi`, `xImage` under `server-side/image/nand/`.
> 
> To build `system.ubi`, you can run command below:
> 
> ```shell
> mkfs.ubifs -d system -e 0x1F000 -c 660 -m 0x800 -o system.ubi
> ```
> 
> where system is ubifs-root directory modified. Some people claimed one of the flag should be `-c 720`, but 660 worked for me.

thank you!

**Comment by tenshi0xx** [comment]
![image](https://github.com/user-attachments/assets/e8dc8a9f-6199-435d-815b-793df3ad18ce)

**Comment by npmania** [comment]
Update fails when `.zip` files aren't properly signed or `md5sum` value of `firmware_v0.tar.gz` is invalid. I've tried on new Linux system today, and also got the same update failed error. Some person on Russian forum claimed that firmware signing might only work with Oracle Java, and that might the problem in this case.

**Comment by npmania** [comment]
I've tried with multiple versions of Oracle JDK, but didn't made it this time. It's been too long since I've succeeded injecting my firmware, so I don't quite remember how I did last time.
I'm also using Shanling M0 Pro. If you're okay, can you send me your IM address to np@mkv.li ? I'm available on Telegram, Discord, IRC and XMPP.
